version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: blog-api
    container_name: blog-api-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - blog-api-network

  db:
    image: mysql:5.7
    container_name: blog-api-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_ROOT_PASSWORD:
    networks:
      - blog-api-network

networks:
  blog-api-network:
    driver: bridge
